### PR TITLE
Limit critical’s concurrency using tiny-async-pool

### LINKED ISSUE #3: Out-of-memory error
Some builds are crashing due to running out of memory:

```
<--- Last few GCs --->
[15157:0x2872030] 70768 ms: Scavenge 1374.6 (1424.2) -> 1373.9 (1424.2) MB, 3.8 / 0.0 ms (average mu = 0.106, current mu = 0.032) allocation failure
[15157:0x2872030] 70778 ms: Scavenge 1374.8 (1424.2) -> 1374.0 (1424.2) MB, 3.8 / 0.0 ms (average mu = 0.106, current mu = 0.032) allocation failure
[15157:0x2872030] 70788 ms: Scavenge 1374.9 (1424.2) -> 1374.2 (1424.7) MB, 4.2 / 0.0 ms (average mu = 0.106, current mu = 0.032) allocation failure
<--- JS stacktrace --->
==== JS stack trace =========================================
0: ExitFrame [pc: 0x2cd14995be1d]
1: StubFrame [pc: 0x2cd14994e6d6]
Security context: 0x036476b9e6c1 <JSObject>
2: replace [0x36476b905c1](this=0x21171492ca99 <String[20]: .qc-guide-box:before>,0x23a2b15d84a1 <JSRegExp <String[59]: :?:before|:?:after|:?:visited|:?:first-letter|:?:first-line>>,0x2fc6142029f1 <String[0]: >)
3: enter [0x3dafe7c7d1d9] [/opt/build/repo/node_modules/penthouse/lib/selectors-profile.js:~96] [pc=0x...
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
1: 0x8fb090 node::Abort() [/opt/buildhome/.nvm/versions/node/v10.20.1/bin/node]
2: 0x8fb0dc [/opt/buildhome/.nvm/versions/node/v10.20.1/bin/node]
3: 0xb031ce v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/opt/buildhome/.nvm/versions/node/v10.20.1/bin/node]
4: 0xb03404 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/opt/buildhome/.nvm/versions/node/v10.20.1/bin/node]
5: 0xef7462 [/opt/buildhome/.nvm/versions/node/v10.20.1/bin/node]
6: 0xef7568 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [/opt/buildhome/.nvm/versions/node/v10.20.1/bin/node]
7: 0xf03642 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/opt/buildhome/.nvm/versions/node/v10.20.1/bin/node]
8: 0xf03f74 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/opt/buildhome/.nvm/versions/node/v10.20.1/bin/node]
9: 0xf06be1 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/opt/buildhome/.nvm/versions/node/v10.20.1/bin/node]
10: 0xed0064 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [/opt/buildhome/.nvm/versions/node/v10.20.1/bin/node]
11: 0x11701ee v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) [/opt/buildhome/.nvm/versions/node/v10.20.1/bin/node]
12: 0x2cd14995be1d
```

Do you know where this might come from?

### PR DESCRIPTION
**Pull request by Tom-Bonnike**
Should resolve #3. Tried locally on a small project and it works. I might need to adjust the concurrency limit later, but I want to try with 4 for now.

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -10,30 +11,36 @@ const getHtmlFiles = async (directory) => {
   return files.map((file) => file.fullPath)
 }
 
+const CRITICAL_CONCURRENCY_LIMIT = 4
```
Comment (Tom-Bonnike) [inline index.js:14]: I’m not sure what a good number is 😅 This will run 4 puppeteer instances at once maximum, it really depends on the machine the build is running on.
Would be sweet to make use of multiple cores as well but hey this will do for now

File: index.js [hunk 2]
```diff
@@ -10,30 +11,36 @@ const getHtmlFiles = async (directory) => {
...
+    }))
 
     try {
       // Ignore penthouse/puppeteer max listener warnings.
       // See https://github.com/pocketjoso/penthouse/issues/250.
       // One penthouse call is made per page and per screen resolution.
-      process.setMaxListeners(htmlFiles.length * inputs.dimensions.length + 1)
+      process.setMaxListeners(
+        CRITICAL_CONCURRENCY_LIMIT * inputs.dimensions.length + 1
+      )
```
Comment (Tom-Bonnike) [inline index.js:36]: I think it still makes sense to silence those warnings.

File: index.js [hunk 3]
```diff
@@ -10,30 +11,36 @@ const getHtmlFiles = async (directory) => {
...
-          base: constants.PUBLISH_DIR,
-          // Overwrite files by passing the same path for `src` and `target`.
-          src: filePath,
-          target: filePath,
-          inline: true,
-          minify: inputs.minify,
-          extract: inputs.extract,
-          dimensions: inputs.dimensions
-        })
+      await asyncPool(
```
Comment (Tom-Bonnike) [inline index.js:38]: The “algorithm” is super sweet: https://github.com/rxaviers/async-pool/blob/master/lib/es7.js

File: index.js (hunk 1 above)
Comment (ehmicky) [reply index.js:14]: Some libraries use `os.cpus().length` for default concurrency limit. Others (like Ava) add a check that decreases this to `2` when CI is detected.

Comment (Tom-Bonnike) [reply index.js:14]: `async-pool` doesn’t handle forking to a new core, and running multiple puppeteer instances in the same process is not actually a problem. It should probably be handled by `critical` or `penthouse` itself.

I think I’ll go with an hardcoded 4 for now, I’ll decrease to 2 if the error still happens.
